server:
  port: 8082

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      
      properties:
        spring.json.trusted.packages: com.kodewala.notification_service.dto
        spring.json.value.default.type: com.kodewala.notification_service.dto.OrderEvent
        spring.json.use.type.headers: false

      # Optional but recommended
      enable-auto-commit: false

  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  kafka:
    topic: order-topic
